name: Java CI with Maven

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          node-version: '16'

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven

      - name: Run Tests
        run: mvn clean test
        continue-on-error: true

      - name: Get Allure history
        uses: actions/checkout@v2
        with:
          ref: gh-pages
          path: gh-pages
        continue-on-error: true

      - name: Generate Allure Report
        id: allure-report
        uses: simple-elf/allure-report-action@master
        with:
          allure_results: target/surefire-reports
          gh_pages: gh-pages
          allure_report: allure-report
          allure_history: allure-history
          keep_reports: 20
        continue-on-error: true

      - name: Deploy Report to Github Pages
        uses: peaceiris/actions-gh-pages@v2
        env:
          PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: allure-history
        if: always()

